### ISSUE TITLE
Write a report on existing DMP tools

### ISSUE THREAD

**Issue by mpejcoch** [metno/S-ENDA-documentation#137] opened 2020-04-23 09:37 UTC

**Comment by mortenwh** [comment] 2020-05-25 13:47
This is coming after the DMP workshop, right?

**Comment by mortenwh** [comment] 2020-06-04 16:34
@mpejcoch - can this be done by 19th June?

**Comment by mortenwh** [comment] 2020-06-08 14:25
Duplicate of metno/S-ENDA-project-plan#137

**Closed by mortenwh** 2020-06-08 14:25 UTC
